### ISSUE TITLE
Fix Deprecation Warning of kd_trees.py

### ISSUE THREAD

**Issue by WinckelData** [raspersc2/queens-sc2#20]
in kd_trees.py the import of cKDTree is deprectated.

For backward-compatibility it could be replaced by:

**from scipy.spatial import KDTree as cKDTree**

else refactoring would be useful.

**Comment by raspersc2** [comment]
Thanks for noticing this, but will be left alone for now since aiarena ladder is on `scipy==1.6.3` https://github.com/aiarena/aiarena-docker/blob/master/requirements.txt#L4

This should be fixed next time aiarena update their libraries
