### ISSUE TITLE
Queens planting tumors too close to other tumors

### ISSUE THREAD

**Issue by goberlan** [raspersc2/queens-sc2#5]
May be this could be a policy option, but it would be helpful to give a limit to how close a queen can plant a tumor to another tumor. Similar to how creep tumors can't plant within a distance of another tumor.

Thanks!

**Comment by raspersc2** [comment]
Thanks for the suggestion, this is now closed via this commit https://github.com/raspersc2/queens-sc2/commit/71a2a3491ab03ae3fc2e554771780a4f4f9e554f

Please report back if there are any issues
